language: ruby
dist: trusty
rvm:
  - '2.3.3'
cache: bundler
before_install: 
  - source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script:
  - source ${TRAVIS_BUILD_DIR}/tools/ci/before_script.sh
services:
  - postgresql
addons:
  postgresql: '9.5'
env:
  - TEST_SUITE=rspec
  - TEST_SUITE=rubocop
  - TEST_SUITE='haml-lint app/views/'
script:
- bin/$TEST_SUITE
bundler_args: --binstubs=./bundler_stubs
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
